chess/urls.py
from django.urls import path
from chess import views

app_name = 'chess'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('play/', views.PlayLobbyView.as_view(), name='playlobby'),
    path('play/<int:game_id>/', views.PlayView.as_view(), name='play'),
    path('play/spectate/<int:game_id>/', views.PlayView.as_view(), name='spectate'),
    path('moveupdate/<int:game_id>/', views.MoveUpdateView.as_view(), name='moveupdate'),
    path('movelist/<int:game_id>/', views.MoveListView.as_view(), name='movelist'),
    path('game-history/<int:game_id>/', views.GameHistoryView.as_view(), name='gamehistory'),
    path('board-history/<int:game_id>/', views.BoardHistoryView.as_view(), name='boardhistory'),
    path('tournament-history/', views.show_tournament_history, name='history'),
    path('tournament/<tournament_name>/', 
         views.show_tournament, name='show_tournament'),
    path('calendar/', views.show_calendar, name='calendar'),
    path('update-calendar/', views.CalendarUpdateView.as_view(), name='updatecalendar'),
    path('accountpage/', views.show_accountpage, name='accountpage'),
    path('accountpage/create/', views.create_accountpage, name='create_accountpage'),
    path('add_tournament/', views.add_tournament, name='add_tournament'),
    path('delete-tournament/', views.DeleteTournamentView.as_view(), name='deletetournament'),
    path('tournament-signup/', views.TournamentSignupView.as_view(), name='tournamentsignup'),
]

chess_tournament_app_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from chess import views

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('chess:create_accountpage')


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('chess/', include('chess.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

chess/models.py
from django.db import models
from django.contrib.auth.models import User
import chess.tasks

# Create your models here.

class Tournament(models.Model):
    name = models.CharField(max_length=50, unique=True)
    date = models.DateTimeField()
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    winner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='winner')
    
    def save(self, *args, **kwargs):
        super(Tournament, self).save(*args, **kwargs)
        chess.tasks.schedule_games(self.id, schedule=self.date)

    def __str__(self):
        return self.name

class Game(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    
    time = models.DateTimeField()
    player_white = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='player_white')
    player_black = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='player_black')

    result = models.DecimalField(max_digits=2, decimal_places=1, null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if self.result is not None:
            print('saving game result...')
            accountpage_white = AccountPage.objects.get_or_create(user=self.player_white)[0]
            accountpage_black = AccountPage.objects.get_or_create(user=self.player_black)[0]

            if self.result == 1.0: # white won
                accountpage_white.wonGame += 1
                accountpage_black.lostGame += 1
            elif self.result == 0.0: # black won
                accountpage_white.lostGame += 1
                accountpage_black.wonGame += 1

            accountpage_white.winRate = accountpage_white.wonGame / (accountpage_white.wonGame + accountpage_white.lostGame)
            accountpage_black.winRate = accountpage_black.wonGame / (accountpage_black.wonGame + accountpage_black.lostGame)

            accountpage_white.save()
            accountpage_black.save()

        super(Game, self).save(*args, **kwargs)

    def __str__(self):
        return self.player_white.username + ' vs ' + self.player_black.username

class Move(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    move_id = models.PositiveIntegerField()
    square_from = models.CharField(max_length=2)
    square_to = models.CharField(max_length=2)

    class Meta:
        unique_together = ('move_id', 'game')

    def save(self, *args, **kwargs):
        existing_ids = Move.objects.filter(game=self.game).order_by('-move_id').values_list('move_id', flat=True)
        if existing_ids:
            self.move_id = existing_ids[0] + 1
        else:
            self.move_id = 0
        super(Move, self).save(*args, **kwargs)

    def __str__(self):
        return self.square_from + self.square_to

class AccountPage(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    status = models.CharField(max_length=100)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    winRate = models.DecimalField(max_digits=3, decimal_places=1, default=0)
    wonGame = models.IntegerField(default=0)
    lostGame = models.IntegerField(default=0)
    
    def __str__(self):
        return self.user.username

chess/forms.py
from django import forms
from chess.models import AccountPage, Tournament
from django.contrib.auth.models import User
from django.utils import timezone

class AccountPageForm(forms.ModelForm):
    status = forms.CharField(max_length=100, help_text="Please enter the status.")
    class Meta:
        model = AccountPage
        fields = ('status', 'picture',)
        
class TournamentForm(forms.ModelForm):
    name = forms.CharField(max_length=50, help_text="Please enter the tournament name.")
    date = forms.SplitDateTimeField(label='Pick date and time:', initial=timezone.now(), widget=forms.SplitDateTimeWidget(date_attrs={'type': 'date'}, time_attrs={'type':'time'}, time_format='%H:%M'))
    class Meta:
        model = Tournament
        fields = ('name', 'date',)

class ChooseTournamentsForm(forms.Form):
    def __init__(self, *args, **kwargs):
        user = None
        if 'user' in kwargs:
            user = kwargs.pop('user')
        super(ChooseTournamentsForm, self).__init__(*args, **kwargs)

        label = "Choose one tournament or more:"

        if user:
            tournament_choices = zip(Tournament.objects.exclude(participants=user).order_by('id').values_list('id', flat=True), 
                                     Tournament.objects.exclude(participants=user).order_by('id').values_list('name', flat=True))
        else:
            tournament_choices = zip(Tournament.objects.all().order_by('id').values_list('id', flat=True), 
                                     Tournament.objects.all().order_by('id').values_list('name', flat=True))

        self.fields['tournaments'] = forms.MultipleChoiceField(choices=tournament_choices,
                                                               label=label,
                                                               widget=forms.CheckboxSelectMultiple(),
                                                               required=False)
    
    

chess/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string
from django.views import View
from chess import gamerules
from chess.models import Tournament, Game, Move, AccountPage
from chess.forms import AccountPageForm, TournamentForm, ChooseTournamentsForm
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils import timezone
from django.utils.decorators import method_decorator
from datetime import timedelta
from copy import deepcopy

class IndexView(View):
    def get(self, request):
        upcoming_tournaments = Tournament.objects.filter(date__gte=timezone.now())
        recent_games = Game.objects.filter(result__isnull=False).order_by('-time')[:5]

        context_dict = {'upcoming_tournaments':upcoming_tournaments, 'recent_games':recent_games}
        return render(request, 'chess/index.html', context_dict)

class PlayView(View):
    def get(self, request, game_id):
        try:
            game = Game.objects.get(id=game_id)

            # if spectate_mode is on, the user will have no control over the game
            spectate_mode = 'spectate' in request.path.split('/')

            if timezone.now() < game.time: # dissalow users from entering games which are scheduled in the future
                return redirect(reverse('chess:index'))
            elif game.result is not None: # if the game has been played already, redirect user to its history page
                return redirect(reverse('chess:gamehistory', kwargs={'game_id':game_id}))

            # perspective decides if the board is shown normal or upside down
            perspective = 0
            if not spectate_mode:
                if request.user.is_authenticated and request.user == game.player_white:
                    perspective = 0
                elif request.user.is_authenticated and request.user == game.player_black:
                    perspective = 1
                else:
                    # user does not participate in this game
                    return redirect(reverse('chess:spectate', kwargs={'game_id':game_id}))

            # execute moves on the board in order
            board_state = deepcopy(gamerules.starting_board_state)
            moves = Move.objects.filter(game=game).order_by('move_id')
            for move in moves:
                gamerules.make_move(board_state, move.square_from, move.square_to)

            context_dict = {'perspective': perspective, 
                            'board_state': board_state, 
                            'moves': [move.square_from + move.square_to for move in moves], 
                            'spectate_mode': spectate_mode,
                            'player_white_name': game.player_white.username,
                            'player_black_name': game.player_black.username}
            
            return render(request, 'chess/play.html', context_dict)
        except Game.DoesNotExist:
            return redirect(reverse('chess:index'))

class PlayLobbyView(View):
    def get(self, request):
        games = Game.objects.filter(time__lte=timezone.now()).filter(result__isnull=True)
        if request.user.is_authenticated:
            ongoing_games = games.exclude(player_black=request.user).exclude(player_white=request.user)
            games_white = games.filter(player_white=request.user)
            games_black = games.filter(player_black=request.user)
            playable_games = (games_white | games_black)
        else:
            ongoing_games = games
            playable_games = Game.objects.none()

        # playable games are the currently held games which the user participates in. ongoing games are all other currently held games.
        context_dict = {'playable_games': playable_games.order_by('time'), 'ongoing_games': ongoing_games.order_by('time') }

        # gamestatus is present if the user has just finished their game. It informs them if they won, lost or drawn the game
        if 'gamestatus' in request.GET:
            gamestatus = request.GET['gamestatus']
            if gamestatus == 'draw':
                context_dict['message'] = "Your game ended in a draw."
            elif gamestatus == 'win':
                context_dict['message'] = "Congratulations! You have won the game."
            elif gamestatus == 'loss':
                context_dict['message'] = "You have lost the game."
        
        return render(request, 'chess/playlobby.html', context_dict)

class MoveListView(View):
    def get(self, request, game_id):
        try:
            game = Game.objects.get(id=game_id)

            # execute moves on the board in order
            board_state = deepcopy(gamerules.starting_board_state)
            moves = Move.objects.filter(game=game).order_by('move_id')
            for move in moves:
                gamerules.make_move(board_state, move.square_from, move.square_to)

            # board_state['turn'] is false when it's white player's turn, true otherwise
            turn = board_state['turn']==(request.user==game.player_black)
            
            move_str = request.GET['move']
            if move_str and (move_str in gamerules.legal_moves(board_state)): # double checks if the received move is valid
                # create a new move in db
                move = Move()
                move.game = game
                move.square_from = move_str[:2]
                move.square_to = move_str[2:]
                move.save()
                # update the board 
                gamerules.make_move(board_state, move.square_from, move.square_to)
                # now is the turn of the opponent
                turn = False

                # check if the current position is winning/losing/tied
                if gamerules.mate_white(board_state):
                    game.result = 0.0 # black won (0-1)
                    game.save()
                elif gamerules.mate_black(board_state):
                    game.result = 1.0 # white won (1-0)
                    game.save()
                elif gamerules.draw(board_state):
                    game.result = 0.5 # draw (1/2-1/2)
                    game.save()

            # if the game is already decided, redirect to playlobby with a message
            if game.result is not None:
                if game.result == 0.5:
                    gamestatus = 'draw'
                elif ((game.result == 0.0 and request.user == game.player_black) or 
                        (game.result == 1.0 and request.user == game.player_white)):
                    gamestatus = 'win'
                else:
                    gamestatus = 'loss'
                return JsonResponse({'redirect':reverse('chess:playlobby')+'?gamestatus='+gamestatus})
            
            return JsonResponse({'turn':turn, 'legal_moves':gamerules.legal_moves(board_state)})
        except Game.DoesNotExist:
            return HttpResponse('')

class MoveUpdateView(View):
    def get(self, request, game_id):
        try:
            game = Game.objects.get(id=game_id)
            moves = Move.objects.filter(game=game).order_by('-move_id')
            if moves:
                # returns the latest move in the game
                return HttpResponse(moves[0].square_from + moves[0].square_to)
            else:
                return HttpResponse('')
        except Game.DoesNotExist:
            return HttpResponse('')
            
class GameHistoryView(View):
    def get(self, request, game_id):
        try:
            game = Game.objects.get(id=game_id)

            if timezone.now() < game.time:
                return redirect(reverse('chess:index'))
            elif game.result is None:
                redirect(reverse('chess:play', kwargs={'game_id':game_id}))

            moves = Move.objects.filter(game=game).order_by('move_id')

            context_dict = { 'moves': [move.square_from + move.square_to for move in moves]}
            return render(request, 'chess/gamehistory.html', context_dict)
        except Game.DoesNotExist:
            return redirect(reverse('chess:index'))

class BoardHistoryView(View):
    def get(self, request, game_id):
        try:
            game = Game.objects.get(id=game_id)
            moves = Move.objects.filter(game=game).order_by('move_id')

            if 'move_index' in request.GET:
                n_moves = int(request.GET['move_index'])
            else:
                n_moves = moves.count()

            board_state = deepcopy(gamerules.starting_board_state)
            for move in moves[:n_moves]:
                gamerules.make_move(board_state, move.square_from, move.square_to)

            context_dict = {'perspective': 0, 
                            'board_state': board_state,
                            'player_white_name': game.player_white.username,
                            'player_black_name': game.player_black.username}
            return HttpResponse(render_to_string('chess/board.html', context_dict))
        except Game.DoesNotExist:
            return HttpResponse('')
        
def show_tournament_history(request):
    context_dict = {}
    
    try:
        tournaments = Tournament.objects.filter(winner__isnull=False)
        
        context_dict['tournaments'] = tournaments
    except Tournament.DoesNotExist:
        context_dict['tournaments'] = None
    
    return render(request, 'chess/tournament_history.html', context=context_dict)

def show_tournament(request, tournament_name):
    context_dict = {}
    
    try:
        tournament = Tournament.objects.get(name=tournament_name)
        games = Game.objects.filter(tournament=tournament)
        
        context_dict['games'] = games
        context_dict['tournament'] = tournament
    except Tournament.DoesNotExist:
        context_dict['games'] = None
        context_dict['tournament'] = None
    

templates/chess/accountpage.html
{% extends 'chess/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Account Page
{% endblock %}

{% block body_block %}
<label for="profile_picture"><h1>{{ user.get_username }}</h1></label>
{% if accountpage.picture %}
<img name="profile_picture" src="{{ MEDIA_URL }}{{accountpage.picture}} " width="100" height="100" alt="Your profile picture"/>
{% endif %}
<div>
	{% if accountpage.status %}
	<h3>Status:</h3><p>{{ accountpage.status }}</p>
	{% endif %}
	<h3>Statistics:</h3>
	<table class="table">
		<tbody>
			<tr>
				<th scope="row">Number of won games:</th>
				<td>{{ accountpage.wonGame }}</td>
			</tr>
			<tr>
				<th scope="row">Number of lost games:</th>
				<td>{{ accountpage.lostGame }}</td>
			</tr>
			<tr>
				<th scope="row">Win rate:</th>
				<td>{{ accountpage.winRate }}</td>
			</tr>
		</tbody>
	</table>
</div>
<a href="{% url 'chess:create_accountpage' %}">Edit account page</a>
{% endblock %}

templates/chess/add_tournament.html
{% extends 'chess/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add a tournament
{% endblock %}

{% block body_block %}

<strong>Add a tournament here!</strong>
<br />
<div>
	<form id="tournament_form" method="post" action="{% url 'chess:add_tournament'%}"
	  enctype="multipart/form-data">
	  
	  {% csrf_token %}
	  
      {{ tournament_form.as_p }}
	  <input type="submit" name="submit" value="Submit" />
	</form>
</div>
{% endblock %}

templates/chess/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	{% block css %}
	{% endblock %}
    <title>
		{% block title_block %}
			Chess Tournament App	
		{% endblock %}
	</title>
</head>
<body>
    <header>
		<nav class="navbar navbar-expand-md navbar-dark bg-dark p-0">
			<a class="navbar-brand" href="{% url 'chess:index' %}"><i data-feather="home"></i>Home</a>
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'chess:playlobby' %}">Play</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'chess:history' %}">Tournament History</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'chess:calendar' %}">Calendar</a>
				</li>
				{% if user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'chess:accountpage' %}">My account</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'auth_logout' %}?next={% url 'chess:index' %}">Logout</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'auth_password_change' %}">Change password</a>
				</li>	 	
				{% endif %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'auth_login' %}">Login</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'registration_register' %}">Register</a>
				</li>
			</ul>
			<div class="navbar-nav">
				{% if user.is_authenticated %}
				<a class="nav-link">Logged in as <strong>{{ user.username }}</strong>.</a>
				{% endif %}
			</div>
		</nav>
    </header>
    {% block body_block %}
    {% endblock %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
	{% block javascript %}
	{% endblock %}
	<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	<script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
	<script type="text/javascript">
		feather.replace();
	</script>
</body>
</html>

templates/chess/board.html
{% load staticfiles %}
{% load chess_template_tags %}
{% get_board perspective board_state player_white_name player_black_name %}

templates/chess/calendar.html
{% extends 'chess/base.html' %}
{% load staticfiles %}

{% block css %}
	<link href="{% static 'fullcalendar/css/main.min.css' %}", rel="stylesheet"/>
{% endblock %}

{% block title_block %}
	Calendar
{% endblock %}


{% block body_block %}
{% if user.is_authenticated %}
<div class="container">
	<nav class="navbar navbar-expand-lg">
		<div class="navbar-brand">Tournament Calendar</div>
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<a href="{% url 'chess:add_tournament' %}" class="nav-link"><i data-feather="plus"></i>Add a tournament</a>
			</li>
			{% if user.is_superuser %}
			<li class="nav-item">
				<a href="{% url 'chess:deletetournament' %}" class="nav-link"><i data-feather="trash-2"></i>Cancel tournaments</a>
			</li>
			{% endif %}
			<li class="nav-item">
				<a href="{% url 'chess:tournamentsignup' %}" class="nav-link"><i data-feather="user-plus"></i>Sign up for tournaments</a>
			</li>
		</ul>
	</nav>
</div>
{% endif %}
<div class="container">
	<div id="calendar"></div>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'fullcalendar/js/main.min.js' %}"></script>
<script src="{% static 'js/initializecalendar.js' %}", type="text/javascript"></script>
{% endblock %}

templates/chess/chessboard.html
{% if perspective %}
<style>
    #chess-board {
        background-image: url('/static/images/chessboard-rotated.png');
    }
</style>
{% else %}
<style>
    #chess-board {
        background-image: url('/static/images/chessboard.png');
    }
</style>
{% endif %}
<div id="chess-board">
    <div style="grid-area: 1 / 1 / 2 / 2;"></div>
    <div style="grid-area: 2 / 2 / 3 / 3;"></div>
    <div style="grid-area: 3 / 3 / 4 / 4;"></div>
    <div style="grid-area: 4 / 4 / 5 / 5;"></div>
    <div style="grid-area: 5 / 5 / 6 / 6;"></div>
    <div style="grid-area: 6 / 6 / 7 / 7;"></div>
    <div style="grid-area: 7 / 7 / 8 / 8;"></div>
    <div style="grid-area: 8 / 8 / 9 / 9;"></div>
    <div style="grid-area: 9 / 9 / 10 / 10;"></div>
    <div style="grid-area: 10 / 10 / 11 / 11;"></div>
    {% autoescape off %}
        {{ init_state }}
    {% endautoescape %}
</div>

templates/chess/create_accountpage.html
{% extends 'chess/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Edit account page
{% endblock %}

{% block body_block %}
<h1>{{ user.get_username }}</h1>

<strong>Create your account page here!</strong>
<br />

<form id="accountpage_form" method="post" action="{% url 'chess:create_accountpage'%}"
	  enctype="multipart/form-data">
	  
	  {% csrf_token %}
	  <!-- as_p method wraps each element in the form in a paragraph (denoted by the <p> HTML tag).
	  This ensures that each element appears on a new line-->
      {{ accountpage_form.as_p }}
	  <input type="submit" name="submit" value="Save" />
</form>

{% endblock %}

templates/chess/delete_tournament.html
{% extends 'chess/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Delete tournaments
{% endblock %}

{% block body_block %}
<div>
	<form method="POST" action=".">
	  
	  {% csrf_token %}
	  
      {{ form.as_p }}
	  <input type="submit" name="submit" value="Submit" />
	</form>
</div>
{% endblock %}

templates/chess/gamehistory.html
{% extends 'chess/base.html' %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/chessboard.css' %}">
{% endblock %}

{% block body_block %}
<div id="chess-board-container"></div>
<button id="prev-move"><i data-feather="chevron-left"></i></button>
<button id="next-move"><i data-feather="chevron-right"></i></button>
<h3>Moves:</h3>
<ol id="move-list">
    {% for move in moves %}
    <li>{{ move }}</li>
    {% endfor %}
</ol>
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/gamehistory.js' %}"></script>  
{% endblock %}

templates/chess/index.html
{% extends 'chess/base.html' %}
{% load staticfiles %}

{% block css %}
	<link href="{% static 'css/list.css' %}", rel="stylesheet"/>
{% endblock %}

{% block title_block %}
	Homepage	
{% endblock %}

{% block body_block %}
<h1 class="jumbotron-heading">Homepage</h1>
<div class="container-fluid">
	<details>
		<summary>Upcoming tournaments which might interest you:</summary>
		<ul>
			{% for tournament in upcoming_tournaments %}
			<li><a href="{% url 'chess:calendar' %}?tournament={{ tournament.id }}">{{ tournament.name }}</a></li>
			{% endfor %}
		</ul>
	</details>
</div>
<div class="container-fluid">
	<details>
		<summary>Recent games:</summary>
		<ul>
			{% for game in recent_games %}
			<li><a href="{% url 'chess:gamehistory' game.id %}">{{ game.player_white }} vs {{ game.player_black }}</a></li>
			{% endfor %}
		</ul>
	</details>
</div>
<hr />
{% endblock %}

templates/chess/play.html
{% extends 'chess/base.html' %}
{% load staticfiles %}
{% load chess_template_tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/chessboard.css' %}">
{% endblock %}

{% block body_block %}
<div id="chess-board-container">
    {% get_board perspective board_state player_white_name player_black_name %}
</div>
<h3>Moves:</h3>
<ol id="move-list">
    {% for move in moves %}
    <li>{{ move }}</li>
    {% endfor %}
</ol>
{% endblock %}

{% block javascript %}
    {% if spectate_mode %}
    <script src="{% static 'js/spectate.js' %}"></script>
    {% else %}
    <script src="{% static 'js/play.js' %}"></script>
    {% endif %}    
{% endblock %}

templates/chess/sign_up_for_tournaments.html
{% extends 'chess/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Sign up for tournaments
{% endblock %}

{% block body_block %}

<strong>Sign up for tournaments here!</strong>
<br />
<div>
	<form method="post" action=".">
	  
	  {% csrf_token %}
	  
      {{ form.as_p }}
	  <input type="submit" name="submit" value="Submit" />
	</form>
</div>
{% endblock %}

templates/chess/tournament.html
<!DOCTYPE html>

{% extends 'chess/base.html' %}
{% load staticfiles %}

{% block title_block %}
	{% if tournament %}
		{{ tournament.name }}
	{% else %}
		Unknown Tournament
	{% endif %}
{% endblock %}

{% block body_block %}
	{% if tournament %}
	<h1>{{ tournament.name }}</h1>
	{% if games %}
	<ul>
		{% for game in games %}
		<li><a href="{% url 'chess:gamehistory' game.id %}">{{ game.player_white }} vs {{ game.player_black}} | time: {{ game.time }}</a></li>
		{% endfor %}
	</ul>
	{% else %}
	<strong>No games currently in tournament.</strong>
	{% endif %}
	{% if tournament.winner %}
	<strong>Winner:</strong> {{ tournament.winner.username }}
	{% endif %}
	<h3>Participants:</h3>
	{% if tournament.participants.all %}
		<ul>
		{% for participant in tournament.participants.all %}
			<li>{{ participant.username }}</li>
		{% endfor %}
		</ul>
	{% else %}
	None yet.
	{% endif %}
	{% else %}
	The specified tournament does not exist.
	{% endif %}
{% endblock %}

templates/chess/tournament_history.html
<!DOCTYPE html>

{% extends 'chess/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Tournament History
{% endblock %}

{% block body_block %}
	<div>
	{% if tournaments %}
		<ul>
		{% for tournament in tournaments %}
			<li><a href="{% url 'chess:show_tournament' tournament.name %}">{{ tournament.name }}</a> | {{ tournament.date }}</li>
		{% endfor %}
		</ul>
	{% else %}
		<strong>There are no tournaments present.</strong>
	{% endif %}
	</div>
{% endblock %}